frr version 8.5
frr defaults traditional
hostname spine2
log syslog informational
service integrated-vtysh-config
!
router bgp 65000
 bgp router-id 10.255.0.2
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 !
 ! Underlay eBGP Peers
 neighbor LEAF_UNDERLAY peer-group
 neighbor LEAF_UNDERLAY remote-as external
 neighbor 10.0.1.3 peer-group LEAF_UNDERLAY
 neighbor 10.0.1.3 description leaf1-s2
 neighbor 10.0.2.3 peer-group LEAF_UNDERLAY
 neighbor 10.0.2.3 description leaf2-s2
 !
 ! Overlay EVPN Route Reflector Peering
 neighbor EVPN_OVERLAY peer-group
 neighbor EVPN_OVERLAY remote-as external
 neighbor EVPN_OVERLAY update-source lo
 neighbor 10.255.0.11 peer-group EVPN_OVERLAY
 neighbor 10.255.0.11 description leaf1-evpn
 neighbor 10.255.0.12 peer-group EVPN_OVERLAY
 neighbor 10.255.0.12 description leaf2-evpn
 !
 address-family ipv4 unicast
  network 10.255.0.2/32
  neighbor LEAF_UNDERLAY activate
  neighbor LEAF_UNDERLAY route-map ALLOW-ALL in
  neighbor LEAF_UNDERLAY route-map ALLOW-ALL out
 exit-address-family
 !
 address-family l2vpn evpn
  neighbor EVPN_OVERLAY activate
  neighbor EVPN_OVERLAY route-reflector-client
 exit-address-family
!
route-map ALLOW-ALL permit 10
!
line vty
!
